variables:
  scratchOrgAlias: 'scratch-org'

trigger:
  - main

pool: Default

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g sfdx-cli
      sfdx --version
    displayName: 'Install SFDX CLI'

  - script: |
      echo $(sfdxAuthUrl) | base64 -d > sfdxAuthUrlFile
      sfdx force:auth:sfdxurl:store -f sfdxAuthUrlFile --setdefaultdevhubusername -a DevHub
    displayName: 'Authenticate to Dev Hub'

  - script: |
      sfdx force:org:create --setalias $scratchOrgAlias --durationdays 1 --setdefaultusername
      sfdx force:source:push
      sfdx force:apex:test:run --resultformat human --wait 10
      sfdx force:apex:test:report
    displayName: 'Deploy to Scratch Org and Run Tests'

  - script: |
      sfdx force:source:deploy --wait 10 --testlevel RunLocalTests --targetusername $scratchOrgAlias
    displayName: 'Deploy Changes to Salesforce Org'

  - script: |
      sfdx force:org:delete --targetusername $scratchOrgAlias --noprompt
    displayName: 'Delete Scratch Org'
