trigger:
  - main

pool: Default

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g sfdx-cli
      sfdx --version
    displayName: 'Install SFDX CLI'

  - script: |
      npm install -g @salesforce/cli@1.73.0
      sf --version
    displayName: 'Install SF CLI'

  - script: |
      echo $(sfdxAuthUrl) | base64 -d > sfdxAuthUrlFile
      sfdx force:auth:sfdxurl:store -f sfdxAuthUrlFile --setdefaultdevhubusername -a DevHub
    displayName: 'Authenticate to Dev Hub'

  - script: |
      sfdx force:org:create -f config/project-scratch-def.json --setalias $(SCRATCHORGALIAS) --durationdays 1 --setdefaultusername --json
    displayName: 'Create Scratch Org'

  - script: |
      sfdx force:source:push
    displayName: 'Push Source to Scratch Org'

  - script: |
      sf apex run test --code-coverage --detailed-coverage --result-format human
    displayName: 'Run Tests'

  - script: |
      sfdx force:source:convert --outputdir deploy-dir
    displayName: 'Convert Source to Metadata API Format'

  - script: |
      sfdx force:mdapi:deploy --checkonly --deploydir deploy-dir
    displayName: 'Validate Changes Against Development Sandbox'

  - script: |
      sfdx force:mdapi:deploy:report --json
    displayName: 'Display Validation Results'
  
  - script: |
      sfdx force:source:deploy --wait 10 --testlevel RunLocalTests --targetusername DevHub
    displayName: 'Deploy Changes to Development Sandbox'

  - script: |
      sfdx force:org:delete --targetusername $(SCRATCHORGALIAS) --noprompt
    displayName: 'Delete Scratch Org'
